"""empty message

Revision ID: 1ada81e330b1
Revises: 
Create Date: 2024-12-02 15:25:13.231461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ada81e330b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('age_range', sa.String(length=5), nullable=True),
    sa.Column('image_urls', sa.String(length=2000), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lego')
    op.drop_table('customer')
    # ### end Alembic commands ###
