"""empty message

Revision ID: 752c2d2ba263
Revises: 456f91bfc0d0
Create Date: 2024-12-03 22:15:24.766318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752c2d2ba263'
down_revision = '456f91bfc0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
